version: '2'
services:
    jhipsterpress08-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/JhipsterPress08/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=JhipsterPress08
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
